allow:
	find . -type f -iname "*.sh" -exec chmod +x {} \;

table_det_demo:
	bash scripts/table_det_demo.sh

table_tsr_demo:
	bash scripts/table_tsr_demo.sh

text_det_demo:
	bash scripts/text_det_demo.sh

text_rec_demo:
	bash scripts/text_rec_demo.sh