allow:
	find . -type f -iname "*.sh" -exec chmod +x {} \;

table_det_demo:
	chmod u+x scripts/table_det.sh
	bash scripts/table_det.sh

table_tsr_demo:
	chmod u+x scripts/table_tsr_demo.sh
	bash scripts/table_tsr_demo.sh