# for training
pretrain: content/checkpoint/vgg_transformer.pth

# url or local path (predict)
weights: content/checkpoint/vgg_transformer.pth

backbone: vgg19_bn
cnn:
    pretrained: True
    # pooling stride size
    ss:
        - [2, 2]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]         
    # pooling kernel size 
    ks:
        - [2, 2]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]
    # dim of ouput feature map
    hidden: 256

